version: '3.8'
services:
  validateTemplate:
    image: azure-marketplace:latest
    restart: "no"
    command: python src/script.py
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - AZURE_SUBSCRIPTION_ID=efdd28a3-55e6-4711-a58b-ab398c259094
